default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: storyline_development
test:
  <<: *default
  database: storyline_test
production:
  <<: *default
  database: storyline_production
  username: storyline
  password: <%= ENV['STORYLINE_DATABASE_PASSWORD'] %>
